config/routes.rb
Meetumea::Application.routes.draw do
  
        constraints(:host => "meetume.com") do
          root :to => redirect("http://www.meetume.com")
          match '/*path', :to => redirect {|params| "http://www.meetume.com/#{params[:path]}"}
        end
        
        constraints(:host => "amongu.com") do
          root :to => redirect("http://www.amongu.com")
          match '/*path', :to => redirect {|params| "http://www.amongu.com/#{params[:path]}"}
        end
      
  resources :comments

  resources :posts

  resources :locations

  resources :communitys
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resources :comments
  end
  
  match '/communitys', to: "communitys#index"
  
  match '/users', to: "users#index"
  match '/profile/info', to: "users#info"

  match '/join', to: "users#new"
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  
  root to: "static_pages#home"
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/posts', to: "static_pages#posts"
  match '/meetups', to: "static_pages#meetups"
  match '/chat', to: "static_pages#chat"
  match '/groups', to: "static_pages#groups"
  match '/web', to: "static_pages#web"
  match '/profile', to: "static_pages#profile"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
end

app/views/layouts/_head.html.erb
	
	
<% if logged_in? %>

<head>
<style media="screen" type="text/css">

.heading {
background-color: #2374ee; 
padding-top:12px;
padding-bottom:30px;
}

.inheading {
width:950px; 
margin:auto;
}

.meetumehead {
font-size:40px;
font-family: myriad pro;
position:relative;
float:left;
}

.logoutbutton {
left:250px;
position:relative;
top:5px;
}

.searchbox {
float:left;
position:relative;
left:120px;
top:5px;

}

.messages {
float:left;
position:relative;
left:40px;

}

.activity {
float:left;
position:relative;
left:60px;

}

.profile {
float:left;
position:relative;
left:185px;

}

</style>
</head>

<div class="heading">
<div class="inheading"><div class="meetumehead"><%= link_to "AmongU", root_path %></div>
  <div class="messages"><a href="/messages"><input type="image" src="/meetumemail.png" width="35" height="35"></a></div>
  <div class="activity"><a href="/activity"><input type="image" src="/worldmeetume.png" width="35" height="35"></a></div>
  <div class="searchbox"><input type="text"></div>
  <div class="profile"><a href="/profile"><input type="image" src="/meetumeprofile.png" width="35" height="35"></a><a href="/profile"><%= current_user.name %></a></div>
  <div class="logoutbutton"><%= link_to "Logout", logout_path, method: "delete" %></div>
  
  </div>
  </div>



<div id="navigation">
	<div id="subnavigation">
<div id="community"><h1><%= render "layouts/location" %></h1></div>
<div id="bottombuttons">
<a href="/"><input type="image" src="/streammeetume.png" width="50" height="50">Stream</a>
<a href="/posts"><input type="image" src="postsmeetume.png" width="50" height="50">Posts</a>
<a href="/meetups"><input type="image" src="/eventsmeetume.png" width="50" height="50">Events</a>
<a href="/chat"><input type="image" src="/chatmeetume.png" width="50" height="50">Chat</a>
<a href="/groups"><input type="image" src="/groupsmeetume.png" width="50" height="50">Groups</a>
</div>
	</div>

<% else %>	
	<div id="heading">
		
		<div id="inheading">
			
	<div id="meetume"><%= link_to "AmongU", root_path %></div>
	
	<div id="city"><%= render "layouts/location" %></div>
	
	<div id="login">
	  <%= form_for(:session, :url => sessions_path) do |f| %>

	      <div id="emailcss"><%= f.label :email %></div>
	      <div id="emailboxcss"><%= f.text_field :email %></div>

	     <div id="passwordcss"> <%= f.label :password %></div>
	      <div id="passboxcss"><%= f.password_field :password %></div>
	
	      <div id="loginbutton"><%= f.submit "Login", :class => "btn btn-large btn-primary", :type => "image", :src => "/blank.png", :width =>"125", :height => "48"%></div>
	    <% end %>
	</div>
	
	
	
	</div>
	
</div>

AmongU connects YOU to EVERYONE AMONG U!

<%= form_for(:user, :url => users_path) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>

<% end %>

<% end %>

	

app/views/layouts/_location.html.erb
<%= @city %>, <%= @state %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="google-site-verification" content="mMWS_zK3HPu2Rw29v8dGUsfCZY7sF75pxRMfT3Gz6lo" />
</head>
<body>

<%= render 'layouts/head' %>
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>